name: Java CI with Gradle

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    # Загрузка JAR-файла как артефакт
    - name: Upload JAR to GitHub Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MurderMysteryUtils-1.0  # Имя артефакта
        path: build/libs/MurderMysteryUtils-1.0.jar  # Путь к JAR файлу

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Create GitHub Release
      id: create_release
      uses: gh-actions/create-release@v1
      with:
        tag_name: 'v1.0.0'  # Укажите версию для релиза
        release_name: 'Release v1.0.0'
        body: '1.0'
        draft: false
        prerelease: false

    - name: Upload JAR to GitHub Release
      uses: gh-actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libs/MurderMysteryUtils-1.0.jar  # Путь к файлу
        asset_name: MurderMysteryUtils-1.0.jar  # Имя файла в релизе
        asset_content_type: application/java-archive
